#! /usr/local/apps/python3/3.6.8-01/bin/python3

import os;
import random;

def MONTH_LEN(year, month):
    if month == 1 or month == 3 or month == 5 or month == 7 or month == 8 or month == 10 or month == 12:
        return 31;
    if month == 4 or month == 6 or month == 9 or month == 11:
        return 30;
    if month == 2:
        res4=year % 4;
        res100=year % 100;
        res400=year % 400;
        if (res4 != 0):
            return 28;
        if (res100 != 0):
            return 29;
        if (res400 != 0):
            return 28;
        return 29;
    print("year=", year, " month=", month)
    print("Error in MONTH_LEN\n");
    os.sys.exit()


def NEXT_MONTH_STRING(sixentstr):
    strYear = sixentstr[0] + sixentstr[1] + sixentstr[2] + sixentstr[3]
    strMonth = sixentstr[4] + sixentstr[5]
    eYear = int(strYear)
    eMonth = int(strMonth);
    if eMonth < 12:
        nMonth = eMonth + 1
        if (nMonth < 10):
            strN = "0" + str(nMonth)
        else:
            strN = str(nMonth)
        return strYear + strN
    return str(eYear + 1) + "01"

def IS_DATE_LOWER(DateLow, DateUpp):
    strLow_Year  = DateLow[0] + DateLow[1] + DateLow[2] + DateLow[3]
    strLow_Month = DateLow[4] + DateLow[5]
    strUpp_Year  = DateUpp[0] + DateUpp[1] + DateUpp[2] + DateUpp[3]
    strUpp_Month = DateUpp[4] + DateUpp[5]
    eLow_Year  = int(strLow_Year)
    eLow_Month = int(strLow_Month)
    eUpp_Year  = int(strUpp_Year)
    eUpp_Month = int(strUpp_Month)
    if eLow_Year < eUpp_Year:
        return True
    if eLow_Year > eUpp_Year:
        return False
    return eLow_Month < eUpp_Month
    



if len(os.sys.argv) != 4:
    print("GRIB_DownloadMonth is used as");
    print("GRIB_DownloadMonth Script [DateBegin] [DateEnd]");
    print("with [DateBegin], [DateEnd] of the form YYYYMM");
    os.sys.exit(1);

Script    = os.sys.argv[1];
DateBegin = os.sys.argv[2];
DateEnd   = os.sys.argv[3];

if IS_DATE_LOWER(DateBegin, DateEnd) == False:
    print("We should have DateBegin < DateEnd")
    print("But here we have DateBegin=", DateBegin, " DateEnd=", DateEnd)
    os.sys.exit(1);



DateCurr=DateBegin
CreatePath=True
while True:
    if DateCurr == DateEnd:
        break;
    strYear = DateCurr[0] + DateCurr[1] + DateCurr[2] + DateCurr[3]
    strMonth = DateCurr[4] + DateCurr[5]
    eYear = int(strYear);
    eMonth = int(strMonth);
    #
    lenMonth = MONTH_LEN(eYear, eMonth);
    f = open(Script, 'r')
    ListLines = f.readlines();
    nbEnt= len(ListLines)
    #
    ThePrefix = "unset"
    for iEnt in range(nbEnt):
        eLine = ListLines[iEnt]
        Utarget = eLine.split("target");
        if len(Utarget) == 2:
            str2 = Utarget[1]
            Ustr2 = str2.split(".")
            str3 = Ustr2[0];
            Ustr3 = str3.split("\"");
            ThePrefix = Ustr3[1];
    if ThePrefix == "unset":
        print("We failed to find the prefix. Error in script or input file")
        os.sys.exit(1);
    if CreatePath:
        ePos=-1
        for iChar in range(len(ThePrefix)):
            if ThePrefix[iChar] == '/':
                ePos=iChar
        if ePos == -1:
            print("Wrong about finding / in ThePrefix")
            os.sys.exit()
        TheSub=ThePrefix[0:ePos]
        TheCommand = "mkdir" + " -p " + TheSub
        os.system(TheCommand);
        CreatePath=False
    #
    FinalFile = ThePrefix + "_" + strYear + "_" + strMonth + ".grb";
    #
    if os.path.exists(FinalFile):
        print("The file FinalFile=" + FinalFile + " exists");
    else:
        Uscriptsplit = Script.split("/");
        NakedFileName = Uscriptsplit[len(Uscriptsplit)-1]
        ScriptB = "/tmp/" + NakedFileName + "_" + str(random.randint(1,1000));
        f2 = open(ScriptB, "w+")
        for iEnt in range(nbEnt):
            eLine = ListLines[iEnt]
            Udate = eLine.split("date");
            Utarget = eLine.split("target");
            if len(Udate) == 2:
                strBegin = strYear + strMonth + "01";
                strEnd = strYear + strMonth + str(lenMonth);
                f2.write("  date    = " + strBegin + "/to/" + strEnd + ",\n");
            else:
                if len(Utarget) == 2:
                    f2.write("  target  = \"" + FinalFile + "\"\n");
                else:
                    f2.write(eLine);
        f2.close();
        #
        TheCommand = "mars" + " " + ScriptB;
        os.system(TheCommand);
    #
    DateCurr = NEXT_MONTH_STRING(DateCurr);

print("Normal termination of the program")
