name: Docker Image ocean_works CI

on:
  # Every day at 5 am.
  schedule:
    - cron: "0 5 * * *"
  # Manually triggered
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t oceanworks:build-env . --file script_docker/Dockerfile
